project:
  pre-render: scripts/clean_render.R
  render:
    - index.qmd

lang: en
title: Dr. Martín Lozano.
subtitle: Curriculum vitae.
date-modified: now
date-format: "MMMM D, YYYY"
  
theme:
  light: flatly
  dark: darkly
  
format: 
  html:
    toc: true
    toc-title: CV sections
    smooth-scroll: true
    anchor-sections: true
    number-sections: false
    toc-location: left
    toc-depth: 2
    page-layout: full
    link-external-newwindow: true
    include-after-body:
      - analytics_resume.html
      - progressbar.html
      - back-to-top.html
    css: styles.css

link-citations: true

